### ISSUE TITLE
All tests fail due to "sc" not being found.

### ISSUE THREAD

**Issue by Solian42** [baileyparker/phf-compilers-tests#23]
If the full path to the sc executable is not defined using `--sc`, All tests fail with the following traceback:

```Traceback (most recent call last):
  File "integration_tests/simple_test/fixtured_test_case.py", line 18, in <lambda>
    return lambda self: self.assertFixture(fixture)
  File "integration_tests/simple_test/fixtured_test_case.py", line 107, in assertFixture
    self.assertFixtureAsArgument(fixture)
  File "integration_tests/simple_test/fixtured_test_case.py", line 116, in assertFixtureAsArgument
    result = self.run_phase(fixture.sim_file_path)
  File "integration_tests/simple_test/test_ast.py", line 19, in run_phase
    return self.runner.run_ast(sim_file, as_stdin)
  File "integration_tests/simple_test/runner.py", line 66, in run_ast
    return self._run(['-a'], sim_file, as_stdin)
  File "integration_tests/simple_test/runner.py", line 89, in _run
    stdout=PIPE, stderr=PIPE, stdin=DEVNULL)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sc': 'sc'`

**Comment by baileyparker** [comment]
Here's probably why:

```
>>> Path('./sc')
PosixPath('sc')
>>> str(Path('./sc'))
'sc'
>>>
```
